enum RessourceType {
  aile,
  alliage,
  bois,
  bourgeon,
  carapace,
  carte,
  cereale,
  champignon,
  clef,
  conteneur,
  coquille,
  costume,
  cuir,
  dofus,
  ecorce,
  essence,
  etoffe,
  familier,
  fersDePercepteur,
  filet,
  fleur,
  fragmentDeCarte,
  fruits,
  galet,
  gelee,
  graine,
  haiku,
  huile,
  laine,
  legume,
  liquide,
  materiel,
  metaria,
  minerai,
  montilier,
  nourriture,
  nowel,
  oeil,
  oeuf,
  orbe,
  oreille,
  os,
  pain,
  parcheminDexperience,
  parcheminDeCaracteristique,
  parcheminDeSortilege,
  patte,
  peau,
  pierreBrute,
  pierrePrecieuse,
  planche,
  plante,
  plume,
  poil,
  poisson,
  poissonComestible,
  potion,
  potionDeForgemagie,
  potionDeTeleportation,
  poudre,
  preparation,
  prisme,
  prysmaradite,
  queue,
  racine,
  ressourceDeCombat,
  ressourceDesSonges,
  ressourceDiverses,
  runeAstrale,
  runeDeForgemagie,
  runeDeTranscendance,
  sacDeRessource,
  seve,
  substrat,
  teinture,
  trophee,
  vetement,
  viande,
  viandeComestible,
  unknown,
}

Map<String, RessourceType> ressourceMap = {
  "Aile": RessourceType.aile,
  "Alliage": RessourceType.alliage,
  "Bois": RessourceType.bois,
  "Bourgeon": RessourceType.bourgeon,
  "Carapace": RessourceType.carapace,
  "Carte": RessourceType.carte,
  "Céréale": RessourceType.cereale,
  "Champignon": RessourceType.champignon,
  "Clef": RessourceType.clef,
  "Conteneur": RessourceType.conteneur,
  "Coquille": RessourceType.coquille,
  "Costume": RessourceType.costume,
  "Cuir": RessourceType.cuir,
  "Dofus": RessourceType.dofus,
  "Écorce": RessourceType.ecorce,
  "Essence de gardien de donjon": RessourceType.essence,
  "Étoffe": RessourceType.etoffe,
  "Familier": RessourceType.familier,
  "Fers de percepteur": RessourceType.fersDePercepteur,
  "Filet": RessourceType.filet,
  "Fleur": RessourceType.fleur,
  "Fruits": RessourceType.fruits,
  "Fragment de carte": RessourceType.fragmentDeCarte,
  "Galet": RessourceType.galet,
  "Gelée": RessourceType.gelee,
  "Graine": RessourceType.graine,
  "Haiku": RessourceType.haiku,
  "Huile": RessourceType.huile,
  "Laine": RessourceType.laine,
  "Légume": RessourceType.legume,
  "Liquide": RessourceType.liquide,
  "Matériel": RessourceType.materiel,
  "Métaria": RessourceType.metaria,
  "Minerai": RessourceType.minerai,
  "Montilier": RessourceType.montilier,
  "Nourriture": RessourceType.nourriture,
  "Nowel": RessourceType.nowel,
  "Œil": RessourceType.oeil,
  "Œuf": RessourceType.oeuf,
  "Orbe": RessourceType.orbe,
  "Oreille": RessourceType.oreille,
  "Os": RessourceType.os,
  "Pain": RessourceType.pain,
  "Parchemin d'expérience": RessourceType.parcheminDexperience,
  "Parchemin de caractéristique": RessourceType.parcheminDeCaracteristique,
  "Parchemin de sortilège": RessourceType.parcheminDeSortilege,
  "Patte": RessourceType.patte,
  "Peau": RessourceType.peau,
  "Pierre brute": RessourceType.pierreBrute,
  "Pierre précieuse": RessourceType.pierrePrecieuse,
  "Planche": RessourceType.planche,
  "Plante": RessourceType.plante,
  "Plume": RessourceType.plume,
  "Poil": RessourceType.poil,
  "Poisson": RessourceType.poisson,
  "Poisson comestible": RessourceType.poissonComestible,
  "Potion": RessourceType.potion,
  "Potion de forgemagie": RessourceType.potionDeForgemagie,
  "Potion de téléportation": RessourceType.potionDeTeleportation,
  "Poudre": RessourceType.poudre,
  "Préparation": RessourceType.preparation,
  "Prisme": RessourceType.prisme,
  "Prysmaradite": RessourceType.prysmaradite,
  "Queue": RessourceType.queue,
  "Racine": RessourceType.racine,
  "Ressource de combat": RessourceType.ressourceDeCombat,
  "Ressource des songes": RessourceType.ressourceDesSonges,
  "Ressources diverses": RessourceType.ressourceDiverses,
  "Rune astrale": RessourceType.runeAstrale,
  "Rune de forgemagie": RessourceType.runeDeForgemagie,
  "Rune de transcendance": RessourceType.runeDeTranscendance,
  "Sac de ressource": RessourceType.sacDeRessource,
  "Sève": RessourceType.seve,
  "Substrat": RessourceType.substrat,
  "Teinture": RessourceType.teinture,
  "Trophée": RessourceType.trophee,
  "Vêtement": RessourceType.vetement,
  "Viande": RessourceType.viande,
  "Viande comestible": RessourceType.viandeComestible,
};

RessourceType ressourceFromString({required String name}) {
  return ressourceMap[name] ?? RessourceType.unknown;
}

// ignore: non_constant_identifier_names
Map<RessourceType, String> RESSOURCE_DATA = {
  RessourceType.aile: "Aile",
  RessourceType.alliage: "Alliage",
  RessourceType.bois: "Bois",
  RessourceType.bourgeon: "Bourgeon",
  RessourceType.carapace: "Carapace",
  RessourceType.carte: "Carte",
  RessourceType.cereale: "Céréale",
  RessourceType.champignon: "Champignon",
  RessourceType.clef: "Clef",
  RessourceType.conteneur: "Conteneur",
  RessourceType.coquille: "Coquille",
  RessourceType.costume: "Costume",
  RessourceType.cuir: "Cuir",
  RessourceType.dofus: "Dofus",
  RessourceType.ecorce: "Écorce",
  RessourceType.essence: "Essence de gardien de donjon",
  RessourceType.etoffe: "Étoffe",
  RessourceType.familier: "Familier",
  RessourceType.fersDePercepteur: "Fers de percepteur",
  RessourceType.filet: "Filet",
  RessourceType.fleur: "Fleur",
  RessourceType.fruits: "Fruits",
  RessourceType.fragmentDeCarte: "Fragment de carte",
  RessourceType.galet: "Galet",
  RessourceType.gelee: "Gelée",
  RessourceType.graine: "Graine",
  RessourceType.haiku: "Haiku",
  RessourceType.huile: "Huile",
  RessourceType.laine: "Laine",
  RessourceType.legume: "Légume",
  RessourceType.liquide: "Liquide",
  RessourceType.materiel: "Matériel",
  RessourceType.metaria: "Métaria",
  RessourceType.minerai: "Minerai",
  RessourceType.montilier: "Montilier",
  RessourceType.nourriture: "Nourriture",
  RessourceType.nowel: "Nowel",
  RessourceType.oeil: "Œil",
  RessourceType.oeuf: "Œuf",
  RessourceType.orbe: "Orbe",
  RessourceType.oreille: "Oreille",
  RessourceType.os: "Os",
  RessourceType.pain: "Pain",
  RessourceType.parcheminDexperience: "Parchemin d'expérience",
  RessourceType.parcheminDeCaracteristique: "Parchemin de caractéristique",
  RessourceType.parcheminDeSortilege: "Parchemin de sortilège",
  RessourceType.patte: "Patte",
  RessourceType.peau: "Peau",
  RessourceType.pierreBrute: "Pierre brute",
  RessourceType.pierrePrecieuse: "Pierre précieuse",
  RessourceType.planche: "Planche",
  RessourceType.plante: "Plante",
  RessourceType.plume: "Plume",
  RessourceType.poil: "Poil",
  RessourceType.poisson: "Poisson",
  RessourceType.poissonComestible: "Poisson comestible",
  RessourceType.potion: "Potion",
  RessourceType.potionDeForgemagie: "Potion de forgemagie",
  RessourceType.potionDeTeleportation: "Potion de téléportation",
  RessourceType.poudre: "Poudre",
  RessourceType.preparation: "Préparation",
  RessourceType.prisme: "Prisme",
  RessourceType.prysmaradite: "Prysmaradite",
  RessourceType.queue: "Queue",
  RessourceType.racine: "Racine",
  RessourceType.ressourceDeCombat: "Ressource de combat",
  RessourceType.ressourceDesSonges: "Ressource des songes",
  RessourceType.ressourceDiverses: "Ressources diverses",
  RessourceType.runeAstrale: "Rune astrale",
  RessourceType.runeDeForgemagie: "Rune de forgemagie",
  RessourceType.runeDeTranscendance: "Rune de transcendance",
  RessourceType.sacDeRessource: "Sac de ressource",
  RessourceType.seve: "Sève",
  RessourceType.substrat: "Substrat",
  RessourceType.teinture: "Teinture",
  RessourceType.trophee: "Trophée",
  RessourceType.vetement: "Vêtement",
  RessourceType.viande: "Viande",
  RessourceType.viandeComestible: "Viande comestible",
};
