enum RessourceType {
  aile,
  alliage,
  bois,
  bourgeon,
  carapace,
  carte,
  cereale,
  champignon,
  clef,
  conteneur,
  coquille,
  costume,
  cuir,
  ecorce,
  essence,
  etoffe,
  familier,
  fersDePercepteur,
  filet,
  fleur,
  fruits,
  galet,
  gelee,
  graine,
  haiku,
  huile,
  laine,
  legume,
  liquide,
  materiel,
  metaria,
  minerai,
  nourriture,
  nowel,
  oeil,
  oeuf,
  orbe,
  oreille,
  os,
  pain,
  parcheminDexperience,
  parcheminDeCaracteristique,
  parcheminDeSortilege,
  patte,
  peau,
  pierreBrute,
  pierrePrecieuse,
  planche,
  plante,
  plume,
  poil,
  poisson,
  poissonComestible,
  potion,
  potionDeForgemagie,
  potionDeTeleportation,
  poudre,
  preparation,
  prisme,
  prysmaradite,
  queue,
  racine,
  ressourceDeCombat,
  ressourceDesSonges,
  ressourceDiverses,
  runeAstrale,
  runeDeForgemagie,
  runeDeTranscendance,
  sacDeRessource,
  seve,
  substrat,
  teinture,
  trophee,
  vetement,
  viande,
  viandeComestible,
  unknown,
}

Map<String, RessourceType> ressourceMap = {
  "Aile": RessourceType.aile,
  "Alliage": RessourceType.alliage,
  "Bois": RessourceType.bois,
  "Bourgeon": RessourceType.bourgeon,
  "Carapace": RessourceType.carapace,
  "Carte": RessourceType.carte,
  "Céréale": RessourceType.cereale,
  "Champignon": RessourceType.champignon,
  "Clef": RessourceType.clef,
  "Conteneur": RessourceType.conteneur,
  "Coquille": RessourceType.coquille,
  "Costume": RessourceType.costume,
  "Cuir": RessourceType.cuir,
  "Écorce": RessourceType.ecorce,
  "Essence de gardien de donjon": RessourceType.essence,
  "Étoffe": RessourceType.etoffe,
  "Familier": RessourceType.familier,
  "Fers de percepteur": RessourceType.fersDePercepteur,
  "Filet": RessourceType.filet,
  "Fleur": RessourceType.fleur,
  "Fruits": RessourceType.fruits,
  "Galet": RessourceType.galet,
  "Gelée": RessourceType.gelee,
  "Graine": RessourceType.graine,
  "Haiku": RessourceType.haiku,
  "Huile": RessourceType.huile,
  "Laine": RessourceType.laine,
  "Légume": RessourceType.legume,
  "Liquide": RessourceType.liquide,
  "Matériel": RessourceType.materiel,
  "Métaria": RessourceType.metaria,
  "Minerai": RessourceType.minerai,
  "Nourriture": RessourceType.nourriture,
  "Nowel": RessourceType.nowel,
  "Œil": RessourceType.oeil,
  "Œuf": RessourceType.oeuf,
  "Orbe": RessourceType.orbe,
  "Oreille": RessourceType.oreille,
  "Os": RessourceType.os,
  "Pain": RessourceType.pain,
  "Parchemin d'expérience": RessourceType.parcheminDexperience,
  "Parchemin de caractéristique": RessourceType.parcheminDeCaracteristique,
  "Parchemin de sortilège": RessourceType.parcheminDeSortilege,
  "Patte": RessourceType.patte,
  "Peau": RessourceType.peau,
  "Pierre brute": RessourceType.pierreBrute,
  "Pierre précieuse": RessourceType.pierrePrecieuse,
  "Planche": RessourceType.planche,
  "Plante": RessourceType.plante,
  "Plume": RessourceType.plume,
  "Poil": RessourceType.poil,
  "Poisson": RessourceType.poisson,
  "Poisson comestible": RessourceType.poissonComestible,
  "Potion": RessourceType.potion,
  "Potion de forgemagie": RessourceType.potionDeForgemagie,
  "Potion de téléportation": RessourceType.potionDeTeleportation,
  "Poudre": RessourceType.poudre,
  "Préparation": RessourceType.preparation,
  "Prisme": RessourceType.prisme,
  "Prysmaradite": RessourceType.prysmaradite,
  "Queue": RessourceType.queue,
  "Racine": RessourceType.racine,
  "Ressource de combat": RessourceType.ressourceDeCombat,
  "Ressource des songes": RessourceType.ressourceDesSonges,
  "Ressources diverses": RessourceType.ressourceDiverses,
  "Rune astrale": RessourceType.runeAstrale,
  "Rune de forgemagie": RessourceType.runeDeForgemagie,
  "Rune de transcendance": RessourceType.runeDeTranscendance,
  "Sac de ressource": RessourceType.sacDeRessource,
  "Sève": RessourceType.seve,
  "Substrat": RessourceType.substrat,
  "Teinture": RessourceType.teinture,
  "Trophée": RessourceType.trophee,
  "Vêtement": RessourceType.vetement,
  "Viande": RessourceType.viande,
  "Viande comestible": RessourceType.viandeComestible,
};

RessourceType ressourceFromString({required String name}) {
  return ressourceMap[name] ?? RessourceType.unknown;
}
